######################################################################
#
# File name : adder_32bits_tb.udo
# Created on: Sun Sep 15 13:42:30 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
