######################################################################
#
# File name : adder_32bits_tb_compile.do
# Created on: Sun Sep 15 14:53:31 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"adder_32bits_tb_time_impl.v" \
"F:/modeltech64_10.4/work/adder_32bits_tb.v" \


quit -force

