######################################################################
#
# File name : adder_32bits_tb_wave.do
# Created on: Sun Sep 15 13:42:30 +0800 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
